### ISSUE TITLE
For RateMyProfessor, "No data could be found for this professor" even though the Professor is on RateMyProfessor

### ISSUE THREAD

**Issue by alanyee** [j-delaney/planner-helper#11]
I am not sure if this bug occurs for other professors, but for Professor John Hoon Lee of Hum 3, the extension states that his data could not be found even though the data is the website: http://www.ratemyprofessors.com/ShowRatings.jsp?tid=1106609

**Comment by j-delaney** [comment]
Thanks for finding that! It looks like the extension is interpreting "Hoon" as a middle name and thus only searching for "John Lee" (he appears in these search results but not in the first page of them). I'll add a special exception in for him in the next version

**Comment by j-delaney** [comment]
I'll be fixing this alongside #13
