### ISSUE TITLE
Should all CAPE information be shown?

### ISSUE THREAD

**Issue by codyli520** [j-delaney/planner-helper#23]
I noticed "Avg Grade Expected" and "Avg Grade Received" sections from CAPE are left out from the plugin display.
   Were they intentionally left out?

**Comment by j-delaney** [comment]
I did intentionally leave that out originally. When looking at CAPEs I usually ignore that field since I prefer just looking at GPA. I could see how people would find it useful though. If you wanted to make a PR to add those fields in I would definitely merge it in
