### ISSUE TITLE
Updated Grade Distributions

### ISSUE THREAD

**Issue by j-delaney** [j-delaney/planner-helper#30]
At the moment, Planner Helper is using [AS Grade Distribution](https://as.ucsd.edu/gradeDistribution) which is out of date. We need to upgrade to using CAPE's grade distribution system. An example of that can be found [here](http://cape.ucsd.edu/responses/CAPEReport.aspx?sectionid=867355). These are up-to-date.

**Comment by cameronellis** [comment]
I'm working on this right now

**Comment by cameronellis** [comment]
Please see pull request #34
