### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by j-delaney** [j-delaney/planner-helper#9]
Right now the icon is a free icon I found online. If anyone has graphic design skills I'd love to see what you come up with for a new icon!

**Comment by masterpavan** [comment]
Here's a quick one. Let me know if you like it!
![plannerhelpericon1](https://cloud.githubusercontent.com/assets/19425282/15351706/6f490904-1c95-11e6-9a20-153fab87c9dc.png)

**Comment by krau612** [comment]
I made this super quickly using the original icon.

![calendar128](https://cloud.githubusercontent.com/assets/10003335/15373864/6e23d95c-1cfc-11e6-92ad-51d20a00265d.png)

**Comment by j-delaney** [comment]
Thank you both for making awesome icons! We're going to go with the icon by @masterpavan. We need to provide the icon as 16x16, 32x32, 48x48, and 128x128 and unfortunately the text in @krau612's doesn't scale well for smaller sizes.

@masterpavan: Could you open a Pull Request with your icon in the `icons/` folder with those different sizes?
